if: branch = master
language: cpp
dist: trusty
sudo: required
compiler:
- gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6
    - libcurlpp-dev
    - libboost-all-dev
    update: true
before_install:
- pip install --user cpp-coveralls
install:
- DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
- mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
- travis_retry wget --no-check-certificate https://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.tar.gz
- echo "91dc9af7345e458eb10c853aa875e591efb7079a045641685ddec8d973c2b2bc *cmake-3.14.0-Linux-x86_64.tar.gz"
  > cmake_sha256.txt
- sha256sum -c cmake_sha256.txt
- tar -xvf cmake-3.14.0-Linux-x86_64.tar.gz > /dev/null
- mv cmake-3.14.0-Linux-x86_64 cmake-install
- PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
- cd ${TRAVIS_BUILD_DIR}
before_script:
- mkdir build
- cd build
- CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DCMAKE_BUILD_TYPE=Release ..
script:
- make
after_success:
- bash <(curl -s https://codecov.io/bash)
